# This is a basic workflow to help you get started with Actions

name: creating APK

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
on: push
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: build apk
      uses: steebchen/flutter@v1.0.0
      with:
        args: build apk --release
